//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thahavuru.DataAccessLayer.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class_Attrubute
    {
        public Class_Attrubute()
        {
            this.IndClasses = new HashSet<IndClass>();
            this.FaceAttributeHierarchies = new HashSet<FaceAttributeHierarchy>();
        }
    
        public int CAttributeId { get; set; }
        public string Name { get; set; }
        public Nullable<int> NumberOfClasses { get; set; }
        public Nullable<bool> IsBiometric { get; set; }
        public string ClassificationTechnique { get; set; }
    
        public virtual ICollection<IndClass> IndClasses { get; set; }
        public virtual ICollection<FaceAttributeHierarchy> FaceAttributeHierarchies { get; set; }
    }
}
