//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thahavuru.DataAccessLayer.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaceAttributeHierarchy
    {
        public int Id { get; set; }
        public int ClassAttribute_AttId { get; set; }
        public int LevelNo { get; set; }
    
        public virtual Class_Attrubute Class_Attrubute { get; set; }
    }
}
